dataset:
  dataset_name: cifar10
  dataset_path: ./data/
  init_ratio: 0.1
  # transform: 
model:
  name: resnet101
optimizer:
  type: adam
  initial_lr: 0.0001
train:
  batch_size: 64
  epochs: 1000
evaluate:
  step_sampling: 0.05
  batch_size: 1000
  