name: dlp

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch
  - pytorch-lightning
  - torchvision
  - ipykernel
  - matplotlib
  - pip
  - tqdm
  - pyyaml
  - pip:
    - pickle5
    - Pygments

