name: dlp

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.5
  - pytorch
  - pytorch-lightning
  - torchvision
  - ipykernel
  - matplotlib
  - pip
  - tqdm
  - pyyaml
  - scipy
  - scikit-learn
  - pip:
    - pickle5
    - wandb

