experiment_name: Initial_Test

seed: 42

# Dataset and Active Learning
dataset:
  name: cifar10
  init_lbl_ratio: 0.1
  val_ratio: 0.1

update_ratio: 0.05
n_runs: 9 # should be one more than the number of sampling updates

device: gpu

smp:
  name: 'cal'
  n_neighs: 10
  neigh_dist: 'kldiv'
#smp:
#  name: 'random'
#smp:
#  name: vaal
#  latent_dim: 32
#  lr: 0.001
#  n_sub_epochs: 1

# Run Hyperparameters
batch_size: 128
n_epochs: 100

optimizer: adam
learning_rate: 0.001
momentum: 0.0

# Architecture
autoenc:
  name: vaal
  z_dim: 32
  kld_weight: 1

cls:
  name: vaal_with_latent
  z_dim: 32