experiment_name: default_configuration

# more than one seed can be set 
seed: 42, 26, 15

# Dataset Configurations
dataset:
  name: cifar10 # name of the dataset (cifar10, cifar100, mnist, fmnist)
  init_lbl_ratio: 0.1 # initial labeled ratio
  val_ratio: 0.1 # validation ratio

update_ratio: 0.05 # update ratio between runs 
n_runs: 9 # number of total runs 
# should be one more than the number of sampling updates

# Device
device: gpu

# Sampler Parameters
#smp:
#  name: 'cal' # sampler type: Contrast
#  n_neighs: 10 # number of neighbors to be considered for CAL
#  neigh_dist: 'kldiv' # 
smp:
  name: 'random'
#smp:
#  name: 'cal_pca'
#  n_neighs: 10
#  n_pca_comp: 32 # latent space dimension (should be consistent with others)
#smp:
#  optimizer: adam
#  lr: 0.0005
#  name: vaal
#  latent_dim: 32 # latent space dimension (should be consistent with others)
#  n_sub_epochs: 1

# Run Hyperparameters
batch_size: 128
n_epochs: 100

# Architecture

embedding:
  use_off_the_shelf_vae: true # if set to true -> set train_vae to false and z_dim in cls to 256 !!!! Also do not use VAAL sampler
  train_vae: false
  optimizer: adam
  lr: 0.0005
enc:
  name: vaal
dec:
  name: vaal
  kld_weight: 1
btk:
  name: vaal
  z_dim: 32 # latent space dimension (should be consistent with others)

off_the_shelf_vae:
  load_from_checkpoint: null
  latent_dim: 32
  use_pretrained_cifar_enc: false
  im_channels: 1
  im_height: 32

cls: # classifier parameters
  optimizer: sgd # classifier optimizer
  lr: 0.01 # learning rate of the optimizer
  name: vaal_with_latent # classifier type (vaal, vaal_with_latent,)
  z_dim: 256