run_name: fashion_mnist_vae

n_epochs: 100
strategy: ddp

dataset:
  data_dir: data
  name: Fashion_MNIST
  do_random_crop: false
  do_horizontal_flip: false

  batch_size: 64
  n_workers: 4


vae:
  load_from_checkpoint: null
  latent_dim: 32
  use_pretrained_cifar_enc: false
  im_channels: 1
  im_height: 32
