experiment_name: test_cifar10_pca32_clsVAAL_smpCAL

seed: 42

# Dataset and Active Learning
dataset:
  name: cifar10
  init_lbl_ratio: 0.02
  val_ratio: 0.01

update_ratio: 0.01
n_runs: 2 # should be one more than the number of sampling updates

device: gpu

#smp:
#  name: 'cal'
#  n_neighs: 10
#  neigh_dist: 'kldiv'
#smp:
#  name: 'random'
smp:
  name: 'cal_pca'
  n_neighs: 10
  n_pca_comp: 32
#smp:
#  optimizer: adam
#  lr: 0.0005
#  name: vaal
#  latent_dim: 32
#  n_sub_epochs: 1

# Run Hyperparameters
batch_size: 128
n_epochs: 2

# Architecture

embedding:
  use_off_the_shelf_vae: true # if set to true -> set train_vae to false and z_dim in cls to 256 !!!! Also do not use VAAL sampler
  train_vae: false
  optimizer: adam
  lr: 0.0005
enc:
  name: vaal
dec:
  name: vaal
  kld_weight: 1
btk:
  name: vaal
  z_dim: 32

off_the_shelf_vae:
  load_from_checkpoint: null
  latent_dim: 32
  use_pretrained_cifar_enc: false
  im_channels: 3
  im_height: 32

cls:
  optimizer: sgd
  lr: 0.01
  name: vaal
  z_dim: 256